development:
  cloud_name: duzt9avdv
  api_key: '593921138548114'
  api_secret: XIGTyn6dY1kQW8ZkbxS1hTYlBGQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: duzt9avdv
  api_key: '593921138548114'
  api_secret: XIGTyn6dY1kQW8ZkbxS1hTYlBGQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: duzt9avdv
  api_key: '593921138548114'
  api_secret: XIGTyn6dY1kQW8ZkbxS1hTYlBGQ
  enhance_image_tag: true
  static_image_support: false
